### ISSUE TITLE
Question: Migration with multiple instances

### ISSUE THREAD

**Issue by MALPI** [smartcat-labs/cassandra-migration-tool-java#17]
Hey there,

I am currently using [this migration tool](https://github.com/Contrast-Security-OSS/cassandra-migration). Since the maintainers are quite unresponsive I'd like to give another framework a try, but only if there is a good reason.

I'd like to know if you support any locking mechanism so that only one instance of all started instances will migrate the schema on upstart?

All the best

**Comment by mgobec** [comment]
Thats one of the improvements we were talking about but never had the need to do it because of the deployment setup. This improvement can be implemented using the LWT and "locking" before migration execution if you have multiple apps running this tool on startup. Feel free to create a pull request if you want to implement this if not, let us know and we will do it.

**Comment by ctamisier** [comment]
Hi !
I am interested in this feature, I will study all this to try to make a PR and dig into Lightweight transactions and "locking" as you mentioned.
So if you have any inputs about this I would be very interested. (I don't know how complex this could be but if it's trivial feel free to do it I would say :) )

Thank so much for this and for this tool !
