### ISSUE TITLE
MigrationResources should return a sorted set instead of relying on insertion order

### ISSUE THREAD

**Issue by jonbarksdale** [smartcat-labs/cassandra-migration-tool-java#27]
Just getting started with this project, and one of the first things I noticed is that the migrations are ordered based on insertion order due to using a LinkedHashSet.  It seems like the intent is for either an ordered set or a unique list.  How do you guys feel about a SortedSet instead?  We could simply create a comparator based on the version, and then everything is run in order in the migration engine.

I'm happy to do the work and submit the patch, I just wanted to vet the idea first.

**Comment by mgobec** [comment]
@jonbarksdale Thanks for getting involved. The idea behind keeping the insertion order is that we do mixed SCHEMA and DATA migrations as part of an application migration execution (for example). That means that if we sort migrations by version number we will mix up the order of SCHEMA and DATA. Does it make sense?

**Comment by jonbarksdale** [comment]
I think I understand.  I was actually curious about the difference between schema and data migrations.  From what I could tell from the classes, they are functionally the same, so was the intent to version in two dimensions? Like the schema is version 5, and the data is version 2?

Schema | Data
-------- | -----
1 create keyspace | 
 2 create table seed | 
 || 1 create seed data
3 alter seed data |
|| 2 migrate seed data

Is that right?

If so, what pushed you toward that over, say, just keeping them version ordered, with a precedence between schema and data?  I'm just trying to get a feel for what you guys considered so I don't end up repeating ideas you've already had and discarded.

**Comment by mgobec** [comment]
Yes that is the reason behind two dimensions. We needed to differentiate schema and data migrations with data migrations usually being executed in background after application start and destructive schema migrations being executed as part of a redeploy process. Initially migration had an enum field marking it one or the other but we switched to typed approach because it makes it easier and more obvious in development.

**Comment by jonbarksdale** [comment]
Ok, cool, I think I understand why the types are distinct.  That still doesn't entirely explain the version's being independent though, as another option would have been something like this:


Schema | Data
-------- | -----
1 create keyspace | 
 2 create table seed | 
 || 3 create seed data
4 alter seed data |
||5 migrate seed data

 or even 

Schema | Data
-------- | -----
1 create keyspace | 
 2 create table seed | 2 create seed data
3 alter seed data |3 migrate seed data

Given your intent, and how flexible Cassandra is, maybe it would have been better to name them ONILNE and OFFLINE instead of DATA and SCHEMA? or maybe BACKGROUND  and IMMEDIATE?  Mostly thinking that because there are some schema changes that could be done online, like adding new column definitions, and some data manipulations that you might prefer doing offline before your app starts.

**Comment by jonbarksdale** [comment]
@mgobec poke.  Also, if there is a better place to have this discussion, please let me know your preferred mode.

**Comment by mgobec** [comment]
@jonbarksdale Sorry I missed to answer you. This is a good place for this discussion. I'll try to answer questions one by one.

1) Versioning is separate because we check for version number uniqueness (or at least we did) so it makes sense to have separate versions for data and schema. That being said there is also a late start scenario where you just execute the latest of schema but none of the data (if the db is empty ie dev setup). Its easier and cleaner to have separate versioning.

2) Naming is exactly that and it makes sense when you start using this migration tool. Some schema and or data migrations can be ran offline and some can be ran in the background. Let say you want to add another field, migrate existing field values and then remove the old field. You would update your application not to use the old field and to start using the new filed. Then as part of a deployment you would run schema migration to add that new field, start the application, migrate existing data and them run schema migration to remove the old field. So naming migrations as background and immediate doesn't make that much sense as data and schema are self explanatory.
